# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d881224d1d6e0901f5227d5d4484a7f284b2cc60bd0821397cf1750b1e710a0ad7406dc8034fb9cdedf0c4852b1348658b4e41020ae1ae5c55bd25f6d737bbc

test:
  secret_key_base: d468b1ed2df5aec21be89b3c97261f3f8f45d3ac3639800a8afaa6fc633f0c87b578f9c1e46bca60c5341496cefa96ae60002f427aa0bbad703a5ae8406b9732

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
